## @section Kubernetes settings
##
image:
  ## @param image.registry sonarr image registry
  ##
  registry: docker.io
  ## @param image.repository sonarr image repository
  ##
  repository: digrouz/sonarr
  ##
  ## @param image.tag sonarr image tag
  ## Ref: https://hub.docker.com/r/digrouz/sonarr/tags
  ##
  tag: "latest"
  ## @param image.pullPolicy sonarr image pull policy
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
## @param fullnameOverride String to override the application name.
##
fullnameOverride: ""
## @section Service Configuration
##
service:
  ## @param service.uid user id running sonarr
  ##
  uid: 12345
  ## @param service.gid group id running sonarr
  ##
  gid: 12345
  ## @param service.autoupgrade apply OS updates inside container at startup
  ##
  autoupgrade: 0
  ## @param service.tz Time Zone
  ##
  tz: Europe/Brussels
ingress:
  webui:
    ## @param ingress.webui.enabled Enable ingress for sonarr webui
    ##
    enabled: true
    ## @param ingress.webui.ingressClassName Ingress class name for sonarr webui ingress
    ##
    ingressClassName: traefik
    ## @param ingress.webui.host Host for sonarr webui ingress
    ##
    host: ""
    ## @param ingress.webui.tls Enable TLS for sonarr webui ingress
    ##
    tls: true
    ## @param ingress.webui.annotations Annotations for sonarr webui ingress
    ##
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: [] 
      cert-manager.io/cluster-issuer: letsencrypt-prod
## @section Storage persistence Configuration
##
persistence:
  config:
    ## @param persistence.config.type Type of persistence for sonarr config
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for sonarr config using a persistent volume claim
    ##
    pvc:
      ## @param persistence.config.pvc.storageClass Storage class for sonarr config
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.config.pvc.existingClaim Existing persistent volume claim for sonarr config
      ## If set, the config will be stored in the existing persistent volume claim
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.config.pvc.size Size of the persistent volume for sonarr config
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for sonarr config using NFS
    ##      
    nfs:
      ## @param persistence.config.nfs.server NFS server for sonarr config
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.config.nfs.path NFS path for sonarr config
      ## If not set, the default NFS path will be used
      ##
      path: ""
  downloads:
    ## @param persistence.downloads.type Type of persistence for sonarr downloads
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for sonarr downloads using a persistent volume claim
    ##
    pvc:
      ## @param persistence.downloads.pvc.storageClass Storage class for sonarr downloads
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.downloads.pvc.accessMode Access mode for sonarr downloads
      ## If not set, the default access mode will be used
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.downloads.pvc.size Size of the persistent volume for sonarr downloads
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for sonarr downloads using NFS
    ##      
    nfs:
      ## @param persistence.downloads.nfs.server NFS server for sonarr downloads
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.downloads.nfs.path NFS path for sonarr downloads
      ## If not set, the default NFS path will be used
      ##
      path: ""
  tvshows:
    ## @param persistence.tvshows.type Type of persistence for sonarr tvshows
    ## If set to pvc, a persistent volume claim will be created
    ## If set to nfs, a network file system will be used
    ##
    type: pvc
    ## Specific persistence options for sonarr tvshows using a persistent volume claim
    ##
    pvc:
      ## @param persistence.tvshows.pvc.storageClass Storage class for sonarr tvshows
      ## If not set, the default storage class will be used
      ##
      storageClass: longhorn
      ## @param persistence.tvshows.pvc.accessMode Access mode for sonarr tvshows
      ## If not set, the default access mode will be used
      ##
      accessMode: ReadWriteOnce
      ## @param persistence.tvshows.pvc.size Size of the persistent volume for sonarr tvshows
      ## If not set, the default size will be used
      ##
      size: 5Gi
    ## Specific persistence options for sonarr tvshows using NFS
    ##      
    nfs:
      ## @param persistence.tvshows.nfs.server NFS server for sonarr tvshows
      ## If not set, the default NFS server will be used
      ##
      server: ""
      ## @param persistence.tvshows.nfs.path NFS path for sonarr tvshows
      ## If not set, the default NFS path will be used
      ##
      path: ""
extraObjects: []

## Extra volumes to be mounted into the Pod
## Example:
## extraVolumes:
##   - name: my-config
##     configMap:
##       name: my-configmap
extraVolumes: []
## Extra volumeMounts to add to the Sonarr container
## Example:
## extraVolumeMounts:
##   - name: my-config
##     mountPath: /etc/my-config
extraVolumeMounts: []

