{{- if eq .Values.persistence.config.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sonarr 
spec:
  accessModes:
    - {{ .Values.persistence.config.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.pvc.size | quote }}
  {{- if .Values.persistence.config.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.config.pvc.storageClass | quote }}
  {{- end }}
{{- end }}
--- 
{{- if eq .Values.persistence.downloads.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-downloads-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sonarr 
spec:
  accessModes:
    - {{ .Values.persistence.downloads.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.pvc.size | quote }}
  {{- if .Values.persistence.downloads.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.downloads.pvc.storageClass | quote }}
  {{- end }}
{{- end }} 
---
{{- if eq .Values.persistence.tvshows.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tvshows-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: sonarr 
spec:
  accessModes:
    - {{ .Values.persistence.tvshows.pvc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.tvshows.pvc.size | quote }}
  {{- if .Values.persistence.tvshows.pvc.storageClass }}
  storageClassName: {{ .Values.persistence.tvshows.pvc.storageClass | quote }}
  {{- end }}
{{- end }}

